### ISSUE TITLE
Alter existing users

### ISSUE THREAD

**Issue by ChristopherRabotin** [influxdb/influxdb-python#107]
There's currently a TODO on it, so I'll just handle that. ;)

**Comment by ChristopherRabotin** [comment]
@ReAzem , if you're happy with this [commit](https://github.com/ChristopherRabotin/influxdb-python/commit/9db53bf7a9f2b1c114e2a64b31623c3ada1b8b01) I'll start writing tests. I think that merging in update_database_user_password with update_database_user_permissions (which currently raises `NotImplementedError`) makes it more similar to `alter_database_admin` and keeps everything in one function. Let me know.

**Comment by ReAzem** [comment]
@ChristopherRabotin This makes perfect sense. I will gladly review/merge this PR.

On another note, I would suggest you take a look at InfluxDB 0.9.0 since the way of altering users will be different. I have started adapting the lib to 0.9.0 on the [0.9.0_support](https://github.com/influxdb/influxdb-python/tree/0.9.0_support) branch. Maybe you would like to work on this feature for 0.9.0 too?

**Comment by ChristopherRabotin** [comment]
Cool, I'll get the tests done this week then.

Sure, I can handle that for 0.9.0 as well. I'll focus on 0.8 first though because that's the version we use at work.

**Comment by ChristopherRabotin** [comment]
Should this issue be closed since user alteration for 0.9 is in #109 ?

**Comment by ReAzem** [comment]
Yep!
