### ISSUE TITLE
Add support for InfluxDB line protocol write API

### ISSUE THREAD

**Issue by victorhooi** [influxdb/influxdb-python#191]
InfluxDB recently introduced a new line protocol write API, for more efficient bulk entry of points:

https://github.com/influxdb/influxdb/pull/2696

It would be awesome if support for this could be added in the Python client!

**Comment by trehn** [comment]
I'd also like to point out that UDP writes are currently broken since JSON over UDP was dropped in 0.9.0 already (in favor of this new line protocol).

Tempted to take a stab at this if @aviau isn't working on it already.

**Comment by aviau** [comment]
@trehn I'm not yet working on it.  Your contribution would be much appreciated!  Go ahead and I'll review :)

**Comment by trehn** [comment]
I have an initial implementation here: https://github.com/trehn/influxdb-python/commits/feature/line-protocol

* So far there is no reason to break backwards compatibility for the Python API.
* I introduced a dependency on python-dateutil in order to parse the string dates the Python API expects. This has the added advantage of allowing more date formats (dateutil will recognize a lot of different formats).
* `datetime` objects can now also be provided as timestamps (pretty much a side effect of parsing the date strings).
* If users want to avoid the performance overhead resulting from date string parsing and `datetime` handling, they can just pass in nanosecond integers.
* This is not implemented yet, but maybe we should use `warnings.warn` to warn people when they're specifying a database while using UDP. Selecting the database is now done on the server side for UDP and cannot be influenced by the client. Silently ignoring the database param might be confusing for users.
* The branch linked to above still has lots of test failures. If someone could take a look at these, it would be much appreciated, as I don't understand all of them (some might be obsolete now etc).

**Comment by ynezz** [comment]
@trehn Thanks for your effort, it seems like InfluxDB is still fast moving target as I had to do following [small fixes](https://github.com/ynezz/influxdb-python/commit/8fe609352d952f31f331250d5319a3b2500af038) on top of your changes to get it working again.

**Comment by aviau** [comment]
Please make sure that the line protocol is optional. Maybe you can open a PR?

**Comment by trehn** [comment]
Why should the line protocol be optional? From what I read in https://github.com/influxdb/influxdb/pull/2696 it sounds like JSON is going away.

I'll merge the changes from @ynezz into my branch and try to get rid of the test failures.

**Comment by aviau** [comment]
> it sounds like JSON is going away.

I didn't catch that at first. You are right then!

**Comment by tima** [comment]
As I understand it, JSON is going away once 1.0 is released, but JSON over TCP is remaining until then. I don't think keeping it around for a bit is such a bad idea since that is not a moving target. By keeping it around you have something functional to fallback on if the new line protocol implementation comes out of sync again.

**Comment by svetomir** [comment]
@aviau When will you add line protocol into your branch?

**Comment by aviau** [comment]
@svetomir I am waiting for a pull request from @trehn

**Comment by adventures91** [comment]
@aviau  Is there a reason this issue is still open line write was merged into master? Is it still not working fully yet?

**Comment by aviau** [comment]
@adventures91 Forgot to close.

... Done!

**Comment by adventures91** [comment]
@aviau cool thanks! Any chance you could add this to a release?

**Comment by aviau** [comment]
Yes, soon!

Until then...

```
pip install https://github.com/influxdb/influxdb-python/archive/master.zip
```
